title: Home Page
description: "For students in computer science to learn about binary and have fun!"
owner_name: John Mortensen
github_username: nighthawkcoders
github_repo: "binary" 
baseurl: "/binary"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/about.md